# Generated by Django 5.2 on 2025-04-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rola',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('secretariat', 'Secretariat'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
