# Generated by Django 5.2 on 2025-04-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rola'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('available', 'Dostępny'), ('busy', 'Zajęty'), ('offline', 'Niedostępny')], default='available', max_length=20),
        ),
    ]
