# Generated by Django 5.2 on 2025-04-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rola',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('secretariat', 'Sekretariat'), ('user', 'Użytkownik')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
