version: '3.9'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    command: ["daphne", "-b", "0.0.0.0", "-p", "3000", "corptalk.asgi:application"]

  redis:
    image: redis:latest
    container_name: redis-status
    ports:
      - "6379:6379"
